//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medvnu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int idUser { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "Ban can nhap ten user")]
        public string UserName { get; set; }
        [DisplayName("PassWord")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ban can nhap mat khau")]
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }

    }
}
